import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { connect } from './browser-helper.mjs';

const browser = await connect();
const { send, evaluate, wait, errors } = browser;
const folder = path.resolve('.verification');
await fs.mkdir(folder, { recursive: true });
const downloadFolder = path.join(folder, `download-${Date.now()}`);
await fs.mkdir(downloadFolder, { recursive: true });
let checks = 0, savedName;
function ok(condition, label) { assert.ok(condition, label); checks++; console.log(`OK ${label}`); }
const click = id => evaluate(`document.getElementById(${JSON.stringify(id)}).click()`);
const change = (id, value) => evaluate(`document.getElementById(${JSON.stringify(id)}).value=${JSON.stringify(value)};document.getElementById(${JSON.stringify(id)}).dispatchEvent(new Event('change',{bubbles:true}));`);
const idle = () => wait('!busy && !transition && !!state');
async function screenshot(name) { const result = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true }); await fs.writeFile(path.join(folder, name), Buffer.from(result.data, 'base64')); }

try {
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1050, deviceScaleFactor: 1, mobile: false });
  await send('Page.navigate', { url: 'http://localhost:5080' });
  await wait('typeof state !== "undefined" && !!state && !transition');
  ok(await evaluate('state.corpos.length === 12 && state.corpos.every(c=>c.nome.startsWith("Corpo ") && c.massa>=1e22 && c.massa<=1e25)'), 'Tela inicia com 12 corpos aleatórios originais');
  ok(await evaluate('document.getElementById("universe-title").textContent === "Universo aleatório"'), 'Interface representa o sistema gravitacional aleatório');
  ok(await evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Layout desktop sem transbordamento');
  await screenshot('desktop.png');
  await click('step-button'); await idle();
  ok(await evaluate('state.iteration === 1 && state.elapsed === 3600'), 'Avanço de uma iteração pelo botão');
  await click('play-button'); await wait('state.iteration >= 4'); await click('play-button'); await idle();
  ok(await evaluate('!running && document.getElementById("status").textContent === "PAUSADO"'), 'Iniciar e pausar funcionam');
  await change('speed', '4');
  ok(await evaluate('document.getElementById("speed").value === "4"'), 'Velocidade de reprodução ajustável');
  await evaluate('document.getElementById("speed").dispatchEvent(new Event("input"))');
  ok(await evaluate('document.getElementById("speed-label").textContent === "4×"'), 'Indicador da velocidade atualizado');
  await click('reset-button');
  ok(await evaluate('state.iteration === 0 && state.elapsed === 0'), 'Restaurar condições iniciais funciona');
  await change('iterations', '3'); await change('timestep', '60');
  await click('play-button'); await wait('!running && state.iteration === 3'); await idle();
  ok(await evaluate('state.elapsed === 180 && document.getElementById("status").textContent === "CONCLUÍDO"'), 'Limite, passo físico e conclusão funcionam');
  await click('reset-button'); await change('iterations', '10000'); await change('timestep', '3600');
  await click('add-body'); await wait('document.getElementById("body-dialog").open');
  await change('body-name', 'Corpo de verificação');
  await evaluate('document.getElementById("body-form").requestSubmit()');
  ok(await evaluate('state.corpos.length === 13 && state.corpos[12].nome === "Corpo de verificação"'), 'Adicionar corpo funciona');
  await click('edit-body'); await change('body-mass', '-1'); await evaluate('document.getElementById("body-form").requestSubmit()');
  ok(await evaluate('document.getElementById("body-form-error").textContent.includes("massa") && state.corpos[12].massa>0'), 'Edição rejeita massa negativa sem corromper o estado');
  await change('body-mass', '6e24'); await evaluate('document.getElementById("body-form").requestSubmit()');
  ok(await evaluate('state.corpos[12].massa === 6e24'), 'Editar massa encapsulada por propriedade funciona');
  await click('edit-body'); await click('remove-body');
  ok(await evaluate('state.corpos.length === 12'), 'Remover corpo funciona');
  await evaluate('document.querySelectorAll(".body-item")[2].click()');
  ok(await evaluate('selected === 2 && document.getElementById("detail-name").textContent === state.corpos[2].nome'), 'Seleção e consulta de propriedades funcionam');
  for (const id of ['trails', 'names', 'grid']) { await click(id); ok(await evaluate(`!document.getElementById(${JSON.stringify(id)}).checked`), `Alternar ${id} funciona`); await click(id); }
  const oldZoom = await evaluate('zoom'); await click('zoom-in'); ok(await evaluate('zoom') > oldZoom, 'Zoom de ampliação funciona');
  await click('zoom-out'); ok(Math.abs(await evaluate('zoom') - oldZoom) < 1e-10, 'Zoom de redução funciona');
  await click('fit-button'); ok(await evaluate('zoom === 1'), 'Enquadramento funciona');
  const canvasBounds = await evaluate('(()=>{const r=canvas.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};})()');
  const pointerX = canvasBounds.x + canvasBounds.width / 2, pointerY = canvasBounds.y + canvasBounds.height / 2;
  const oldCenter = await evaluate('({...center})');
  await send('Input.dispatchMouseEvent', { type: 'mousePressed', x: pointerX, y: pointerY, button: 'left', clickCount: 1 });
  await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: pointerX + 55, y: pointerY + 30, button: 'left', buttons: 1 });
  await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: pointerX + 55, y: pointerY + 30, button: 'left', clickCount: 1 });
  ok(await evaluate('center.x') !== oldCenter.x && await evaluate('center.y') !== oldCenter.y, 'Arrastar a visualização funciona com eventos reais');
  const beforeWheel = await evaluate('zoom');
  await send('Input.dispatchMouseEvent', { type: 'mouseWheel', x: pointerX, y: pointerY, deltaX: 0, deltaY: -120 });
  await wait(`zoom > ${beforeWheel}`);
  ok(await evaluate('zoom') > beforeWheel, 'Zoom pelo scroll do mouse funciona');
  await click('fit-button');
  const bodyPoint = await evaluate('(()=>{const p=toScreen(state.corpos[1].posX,state.corpos[1].posY),r=canvas.getBoundingClientRect();return {x:r.x+p.x,y:r.y+p.y};})()');
  await send('Input.dispatchMouseEvent', { type: 'mousePressed', x: bodyPoint.x, y: bodyPoint.y, button: 'left', clickCount: 1 });
  await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: bodyPoint.x, y: bodyPoint.y, button: 'left', clickCount: 1 });
  ok(await evaluate('selected === 1'), 'Selecionar um corpo diretamente no canvas funciona');
  await evaluate('document.activeElement.blur()');
  const oldIteration = await evaluate('state.iteration');
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: ' ', code: 'Space', windowsVirtualKeyCode: 32 });
  await send('Input.dispatchKeyEvent', { type: 'keyUp', key: ' ', code: 'Space', windowsVirtualKeyCode: 32 });
  await wait(`state.iteration > ${oldIteration}`);
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: ' ', code: 'Space', windowsVirtualKeyCode: 32 });
  await send('Input.dispatchKeyEvent', { type: 'keyUp', key: ' ', code: 'Space', windowsVirtualKeyCode: 32 });
  await idle(); ok(await evaluate('!running'), 'Atalho de espaço inicia e pausa a simulação');
  await evaluate('document.activeElement.blur()');
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: '+', code: 'Equal' });
  ok(await evaluate('zoom > 1'), 'Atalho de ampliação funciona');
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'f', code: 'KeyF' });
  ok(await evaluate('zoom === 1'), 'Atalho de enquadramento funciona');
  await click('help-button'); ok(await evaluate('document.getElementById("help-dialog").open'), 'Guia de ajuda disponível');
  await evaluate('document.querySelector("#help-dialog .close-dialog").click()');
  await change('body-count', '8'); await click('generate-button'); await wait('document.getElementById("confirm-dialog").open'); await click('confirm-ok'); await wait('state.corpos.length === 8'); await idle();
  ok(await evaluate('state.corpos.length === 8 && state.iteration === 0'), 'Nova geração respeita quantidade e confirmação');
  await click('save-button'); await idle();
  savedName = await evaluate('document.getElementById("toast").textContent.match(/universo_[0-9]+[.]txt/)?.[0]');
  ok(!!savedName, 'Salvar gera arquivo local');
  await click('library-button'); await wait('document.getElementById("library-dialog").open');
  ok(await evaluate(`document.getElementById('saved-list').textContent.includes(${JSON.stringify(savedName)})`), 'Biblioteca lista o arquivo salvo');
  await evaluate(`Array.from(document.querySelectorAll('.saved-item')).find(r=>r.textContent.includes(${JSON.stringify(savedName)})).querySelector('button').click()`);
  await wait('document.getElementById("confirm-dialog").open'); await click('confirm-ok'); await wait(`document.getElementById('universe-title').textContent===${JSON.stringify(savedName)}`); await idle();
  ok(await evaluate(`state.corpos.length===8 && document.getElementById('universe-title').textContent===${JSON.stringify(savedName)}`), 'Carregar arquivo salvo funciona');
  await send('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: downloadFolder });
  await click('export-button'); await idle();
  for (let i = 0; i < 50; i++) { try { await fs.access(path.join(downloadFolder, 'universo_exportado.txt')); break; } catch { await new Promise(r=>setTimeout(r,100)); } }
  const exported = await fs.readFile(path.join(downloadFolder, 'universo_exportado.txt'), 'utf8');
  ok(exported.startsWith('8;'), 'Exportar baixa arquivo real');
  await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File([${JSON.stringify(exported)}],'teste.txt',{type:'text/plain'}));const input=document.getElementById('import-file');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await wait('document.getElementById("confirm-dialog").open'); await click('confirm-ok'); await wait('document.getElementById("universe-title").textContent === "teste.txt"'); await idle();
  ok(await evaluate('state.corpos.length === 8 && document.getElementById("universe-title").textContent === "teste.txt"'), 'Importar arquivo pelo controle funciona');
  await click('library-button'); await wait('document.getElementById("library-dialog").open');
  await evaluate(`Array.from(document.querySelectorAll('.saved-item')).find(r=>r.textContent.includes(${JSON.stringify(savedName)})).querySelectorAll('button')[1].click()`);
  await wait('document.getElementById("confirm-dialog").open'); await click('confirm-ok'); await wait('document.getElementById("library-dialog").open');
  ok(await evaluate(`!document.getElementById('saved-list').textContent.includes(${JSON.stringify(savedName)})`), 'Excluir arquivo de teste com confirmação funciona'); savedName = undefined;
  await evaluate('document.getElementById("library-dialog").close()');
  await change('body-count', '12'); await click('new-button'); await wait('document.getElementById("confirm-dialog").open'); await click('confirm-ok'); await wait('state.corpos.length === 12'); await idle();
  ok(await evaluate('state.corpos.length === 12'), 'Novo universo funciona');
  await screenshot('desktop.png');
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await evaluate('new Promise(r=>setTimeout(r,150))');
  ok(await evaluate('document.documentElement.scrollWidth <= innerWidth'), 'Layout mobile sem transbordamento');
  await screenshot('mobile.png');
  ok(errors.length === 0, `Sem exceções JavaScript (${errors.join('; ')})`);
  console.log(`\n${checks} verificações de navegador passaram. Capturas em .verification.`);
} finally {
  if (savedName) await fetch(`http://localhost:5080/api/universes/${savedName}`, { method: 'DELETE' });
  browser.close();
}
